#database.yml

# Para conectar o Arachni em uma instancia recem criada do Postgres faca o seguinte:
#sudo -u postgres psql postgres 
# \password postgres
# \q
# CREATE DATABASE arachni_production TEMPLATE template0;
# CREATE USER arachni WITH PASSWORD 'secret' CREATEDB;
#
# Configure o banco de dados e deixe-o pronto para o Arachni
#./arachni/bin/arachni_web_task db:create
#./arachni/bin/arachni_web_task db:migrate
#./arachni/bin/arachni_web_task db:setup
#
#   CREATE USER arachni WITH PASSWORD 'secret' CREATEDB;
#
# (Atualize as credenciais acima e abaixo da forma correta ou o Arachni nao vai conectar)

development:
  host: <%= ENV['POSTGRES_HOST'] %>
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['POSTGRES_DATABASE'] %>
  pool: 50
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test: &test
  host: <%= ENV['POSTGRES_HOST'] %>
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['POSTGRES_DATABASE'] %>
  pool: 50
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

production:
  host: <%= ENV['POSTGRES_HOST'] %>
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['POSTGRES_DATABASE'] %>
  pool: 50
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

cucumber:
  <<: *test

